const CONSTANTS = {

	// for sing -in
	LOGIN_REQUEST: 'LOGIN_REQUEST',
	LOGIN_SUCCESS: 'LOGIN_SUCCESS',
	LOGIN_FAILURE: 'LOGIN_FAILURE',

	// for sing-up
	SINGUP_REQUEST: 'SINGUP_REQUEST',
	SINGUP_SUCCESS: 'SINGUP_SUCCESS',
	SINGUP_FAILURE: 'SINGUP_FAILURE',

	//  get user profile 
	GET_USER_PROFILE_REQUEST: 'GET_USER_PROFILE_REQUEST',
	GET_USER_PROFILE_SUCCESS: 'GET_USER_PROFILE_SUCCESS',
	GET_USER_PROFILE_FAILURE: 'GET_USER_PROFILE_FAILURE',

//  get Car List 
	GET_CAR_LIST_REQUEST: 'GET_CAR_LIST_REQUEST',
	GET_CAR_LIST_SUCCESS: 'GET_CAR_LIST_SUCCESS',
	GET_CAR_LIST_FAILURE: 'GET_CAR_LIST_FAILURE',

	//  get Car Details 
	GET_CAR_DETAILS_REQUEST: 'GET_CAR_DETAILS_REQUEST',
	GET_CAR_DETAILS_SUCCESS: 'GET_CAR_DETAILS_SUCCESS',
	GET_CAR_DETAILS_FAILURE: 'GET_CAR_DETAILS_FAILURE',


	//  get Car Const 
	GET_CAR_COMMON_REQUEST: 'GET_CAR_COMMON_REQUEST',
	GET_CAR_COMMON_SUCCESS: 'GET_CAR_COMMON_SUCCESS',
	GET_CAR_COMMON_FAILURE: 'GET_CAR_COMMON_FAILURE',

	//  get Car Delete 
	GET_CAR_DELETE_REQUEST: 'GET_CAR_DELETE_REQUEST',
	GET_CAR_DELETE_SUCCESS: 'GET_CAR_DELETE_SUCCESS',
	GET_CAR_DELETE_FAILURE: 'GET_CAR_DELETE_FAILURE',

	GET_COMMON_REQUEST: 'GET_COMMON_REQUEST',
	GET_COMMON_SUCCESS: 'GET_COMMON_SUCCESS',
	GET_COMMON_FAILURE: 'GET_COMMON_FAILURE',




}

export default CONSTANTS